# spring:
#   cloud:
#     config:
#       server:
#         git:
#           uri: https://github.com/Bablu682/Controls-Plm-Ms-ymlFile.git
          
          
# #cloud:
# #    config:
# #      enabled: true

# server:
#   port: 8888

#===================================================
server:
  port: 8888
spring:
  application:
    name: config-server     
  profiles:
    active: development-cloud       
  cloud:
    config:
      enabled: false # note this needs to be turned on if you wnat the config server to work
      server:
         git:
          uri: https://github.com/Bablu682/Controls-Plm-Ms-ymlFile.git
          
logging:
  file: F://application_logs/${spring.application.name}.log
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.cloud.config.server: DEBUG  
    #org.springframework: 'OFF'
    #com.netflix.discovery: 'OFF'
    #org.springframework.cloud: 'DEBUG'      



