spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bablu682/Controls-Plm-Ms-ymlFile.git
          
          
#cloud:
#    config:
#      enabled: true

server:
  port: 8888
